cmake_minimum_required(VERSION 3.0)
cmake_policy(SET CMP0011 NEW)

include("${CMAKE_CURRENT_LIST_DIR}/megaAVR.cmake")

set(ATMEGA2560_FLAGS "-D__AGILIB_CPU_AVR_megaAVR_ATmega2560 -mmcu=atmega2560")
set(__AGILIB_CPU                  "ATmega2560")
set(__AGILIB_CPU_megaAVR_ATmega2560 "TRUE")

set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} ${ATMEGA2560_FLAGS}" CACHE STRING "")
set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS}   ${ATMEGA2560_FLAGS}" CACHE STRING "")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${ATMEGA2560_FLAGS}" CACHE STRING "")

unset(ATMEGA2560_FLAGS)
